P129Allup/P129Allup/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using P129Allup.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using P129Allup.Models;
using Newtonsoft.Json;
using P129Allup.ViewModels.BasketViewModels;
using Microsoft.AspNetCore.Authorization;

namespace P129Allup.Controllers
{
    //[Authorize(Roles ="Member,SuperAdmin")]
    public class ProductController : Controller
    {
        private readonly AppDbContext _context;

        public ProductController(AppDbContext context)
        {
            _context = context;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Products.ToListAsync());
            //return Json(await _context.Products.ToListAsync());
        }

        //[Authorize(Roles ="Member")]
        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            Product product = await _context.Products
                .Include(p => p.ProductImages)
                .Include(p => p.Brand)
                .Include(p => p.ProductTags).ThenInclude(pt => pt.Tag)
                .FirstOrDefaultAsync(p => p.Id == id);

            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        public async Task<IActionResult> DetailForModal(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            Product product = await _context.Products
                .Include(p => p.ProductImages)
                .Include(p => p.Brand)
                .Include(p => p.ProductTags).ThenInclude(pt => pt.Tag)
                .FirstOrDefaultAsync(p => p.Id == id);

            if (product == null)
            {
                return NotFound();
            }

            return PartialView("_ProductModalPartial", product);
        }

        //public async Task<IActionResult> Search(string search)
        //{
        //    List<Product> products = await _context.Products
        //        .Where(p => p.Name.ToLower().Contains(search.Trim().ToLower()) || p.Brand.Name.ToLower().Contains(search.Trim().ToLower()))
        //        .ToListAsync();

        //    return Json(new { products});
        //}
        public async Task<IActionResult> Search(string search)
        {
            List<Product> products = await _context.Products
                .Where(p => p.Name.ToLower().Contains(search.ToLower()) ||
                p.Brand.Name.ToLower().Contains(search.ToLower()) || 
                p.ProductTags.Any(pt => pt.Tag.Name.ToLower().Contains(search.ToLower()))).ToListAsync();

            return PartialView("_SearchPartial", products);
        }

        

    }
}

P129Allup/P129Allup/ViewComponents/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using P129Allup.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace P129Allup.ViewComponents
{
    public class FooterViewComponent : ViewComponent
    {
        private readonly AppDbContext _context;

        public FooterViewComponent(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync(IDictionary<string, string> settings)
        {
            //IDictionary<string, string> settings = await _context.Settings.ToDictionaryAsync(x => x.Key, s => s.Value);

            return View(await Task.FromResult(settings));
        }
    }
}

P129Allup/P129Allup/ViewComponents/HeaderViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using P129Allup.DAL;
using P129Allup.Models;
using P129Allup.ViewModels.BasketViewModels;
using P129Allup.ViewModels.HeaderViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace P129Allup.ViewComponents
{
    public class HeaderViewComponent : ViewComponent
    {
        private readonly AppDbContext _context;
        private readonly UserManager<AppUser> _userManager;

        public HeaderViewComponent(AppDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IViewComponentResult> InvokeAsync(IDictionary<string, string> settings)
        {
            //IDictionary<string, string> settings = await _context.Settings.ToDictionaryAsync(x => x.Key, x => x.Value);

            List<BasketVM> basketVMs = null;

            string basket = HttpContext.Request.Cookies["basket"];

            if (!string.IsNullOrWhiteSpace(basket))
            {
                basketVMs = JsonConvert.DeserializeObject<List<BasketVM>>(basket);

                if (User.Identity.IsAuthenticated)
                {
                    AppUser appUser = await _userManager.Users.Include(u => u.Baskets).FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);

                    if (appUser.Baskets != null && appUser.Baskets.Count() > 0)
                    {
                        foreach (var item in appUser.Baskets)
                        {
                            if (!basketVMs.Any(b => b.ProductId == item.ProductId))
                            {
                                BasketVM basketVM = new BasketVM
                                {
                                    ProductId = item.ProductId,
                                    Count = item.Count
                                };

                                basketVMs.Add(basketVM);
                            }
                        }

                        basket = JsonConvert.SerializeObject(basketVMs);

                        HttpContext.Response.Cookies.Append("basket", basket);
                    }
                }

                foreach (BasketVM basketVM in basketVMs)
                {
                    Product product = await _context.Products.FirstOrDefaultAsync(p => p.Id == basketVM.ProductId);

                    basketVM.Image = product.MainImage;
                    basketVM.Name = product.Name;
                    basketVM.ExTax = product.ExTax;
                    basketVM.Price = product.DiscoutnPrice > 0 ? product.DiscoutnPrice : product.Price;
                }
            }
            else
            {
                basketVMs = new List<BasketVM>();
            }

            HeaderViewModel headerViewModel = new HeaderViewModel
            {
                Settings = settings,
                BasketVMs = basketVMs
            };
            return View(await Task.FromResult(headerViewModel));
        }
    }
}

P129Allup/P129Allup/Views/Shared/_BasketIndexPartial.cshtml
@model List<BasketVM>

<div class="col-xl-8">
    <div class="shopping-cart mt-25">
        <h4 class="allup-title">Shopping Cart</h4>

        <div class="shopping-cart-table table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th class="image">Image</th>
                        <th class="product">Product</th>
                        <th class="price">Price</th>
                        <th class="quantity">Quantity</th>
                        <th class="total">Total</th>
                        <th class="delete">Delete</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (BasketVM basketVM in Model)
                    {
                        <tr>
                            <td>
                                <div class="product-image ">
                                    <img style="width:100px" src="~/assets/images/product/@basketVM.Image" alt="cart">
                                </div>
                            </td>
                            <td>
                                <div class="product-title">
                                    <h4 class="title"><a href="single-product.html">@basketVM.Name</a></h4>
                                </div>
                            </td>
                            <td>
                                <div class="product-price">
                                    <span class="price">€@basketVM.Price.ToString("F2")</span>
                                </div>
                            </td>
                            <td>
                                <div class="product-quantity">
                                    <div class="quantity mt-15 d-flex">
                                        <a class="subCount btn" asp-controller="basket" asp-action="UpdateCount" asp-route-id="@basketVM.ProductId"><i class="fal fa-minus"></i></a>
                                        <input type="text" value="@basketVM.Count" />
                                        <a class="addCount btn" asp-controller="basket" asp-action="UpdateCount" asp-route-id="@basketVM.ProductId"><i class="fal fa-plus"></i></a>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <div class="product-total">
                                    <span class="total-amount">€@(basketVM.Count * basketVM.Price)</span>
                                </div>
                            </td>
                            <td>
                                <div class="product-delete">
                                    <a class="deletefromcartbtn" asp-controller="basket" asp-action="DeleteFromCart" asp-route-id="@basketVM.ProductId"><i class="fal fa-trash-alt"></i></a>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="col-xl-4">
    <div class="row">
        <div class="col-xl-12 col-md-6">
            <div class="cart-coupon mt-30">
                <h5 class="title">Discount Coupon Code</h5>
                <form action="#">
                    <div class="single-form coupon-form d-flex flex-wrap">
                        <input type="text" placeholder="Coupon Code">
                        <button class="main-btn">Apply Coupon</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-xl-12 col-md-6">
            <div class="cart-total mt-30">
                <div class="sub-total">
                    <div class="single-total">
                        <span class="cart-value">Subtotal</span>
                        <span class="cart-amount">€@(Model.Sum(b=>b.Count * b.Price) + Model.Sum(b=>b.Count * b.ExTax))</span>
                    </div>
                    <div class="single-total">
                        <span class="cart-value">Shipping Cost</span>
                        <span class="cart-amount">€3.90</span>
                    </div>
                </div>
                <div class="total">
                    <div class="single-total">
                        <span class="cart-value">Total (tax excl.)</span>
                        <span class="cart-amount">€22.80</span>
                    </div>
                    <div class="single-total">
                        <span class="cart-value">Taxes</span>
                        <span class="cart-amount">€0.00</span>
                    </div>
                </div>
                <div class="cart-total-btn text-right">
                    <a class="main-btn" href="#">Proceed to Checkout</a>
                </div>
            </div>
        </div>
    </div>
</div>

P129Allup/P129Allup/Views/Shared/_BasketPartial.cshtml
@model List<BasketVM>


<div class="cart-btn webelement">
    <a asp-controller="basket" asp-action="index">
        <i class="icon ion-bag"></i>
        <span class="text">Cart :</span>
        <span class="total">$@(Model.Sum(b=>b.Count * b.Price)+Model.Sum(b=>b.ExTax * b.Count))</span>
        <span class="count">@Model.Count</span>
    </a>
</div>
<a href="#" class="mobileelement">
    <i class="fal fa-shopping-cart"></i>
    <span>@Model.Count</span>
</a>
<div class="mini-cart">
    <ul class="cart-items">
        @foreach (BasketVM basketVM in Model)
        {
            <li>
                <div class="single-cart-item d-flex">
                    <div class="cart-item-thumb">
                        <a asp-controller="Product" asp-action="Detail" asp-route-id="@basketVM.ProductId"><img src="/assets/images/product/@basketVM.Image" alt="product"></a>
                        <span class="product-quantity">@(basketVM.Count)x</span>
                    </div>
                    <div class="cart-item-content media-body">
                        <h5 class="product-name"><a href="single-product.html">@basketVM.Name</a></h5>
                        <span class="product-price">€@basketVM.Price</span>
                        <a asp-controller="basket" asp-action="deletefrombasket" asp-route-id="@basketVM.ProductId" class="product-close deletefrombasket"><i class="fal fa-times"></i></a>
                    </div>
                </div>
            </li>
        }
    </ul>
    <div class="price_content">
        <div class="cart-subtotals">
            <div class="products price_inline">
                <span class="label">Subtotal</span>
                <span class="value">€@(Model.Sum(b=>b.Price * b.Count))</span>
            </div>
            <div class="tax price_inline">
                <span class="label">Taxes</span>
                <span class="value">€@(Model.Sum(b=>b.ExTax * b.Count))</span>
            </div>
        </div>
        <div class="cart-total price_inline">
            <span class="label">Total</span>
            <span class="value">€@(Model.Sum(b => b.ExTax * b.Count) + Model.Sum(b => b.Price * b.Count))</span>
        </div>
    </div> <!-- price content -->
    <div class="checkout text-center">
        <a href="checkout.html" class="main-btn">Checkout</a>
    </div>
</div> <!-- mini cart -->

P129Allup/P129Allup/Views/Shared/_HomeProductPartial.cshtml
@model List<Product>

<div class="product-items">
    <div class="row product-active">
        @for (int i = 0; i < Math.Round((decimal)Model.Count / 2); i++)
        {
            <div class="col-lg-2">
                @foreach (Product product in Model.Skip(i * 2).Take(2))
                {
                    <div class="single-product mt-30">
                        <div class="product-image">
                            <a href="single-product.html">
                                <img class="first-image" src="~/assets/images/product/@product.MainImage" alt="product">
                                <img class="second-image" src="~/assets/images/product/@product.HoverImage" alt="product">
                            </a>
                            <ul class="product-meta">
                                <li><a asp-controller="basket" asp-action="AddToBasket" asp-route-id="@product.Id" class="addbasket"><i class="icon ion-bag"></i></a></li>
                                <li><a href="#"><i class="icon ion-android-favorite-outline"></i></a></li>
                                <li><a href="#"><i class="icon ion-android-options"></i></a></li>
                                <li><a data-toggle="modal" data-target="#productQuickModal" asp-controller="product" asp-action="DetailForModal" asp-route-id="@product.Id" class="modaldetail"><i class="icon ion-android-open"></i></a></li>
                            </ul>
                        </div>
                        <div class="product-content">
                            <ul class="product-rating">
                                <li><i class="fas fa-star"></i></li>
                                <li><i class="fas fa-star"></i></li>
                                <li><i class="fas fa-star"></i></li>
                                <li><i class="fas fa-star"></i></li>
                                <li><i class="fas fa-star"></i></li>
                            </ul>
                            <h4 class="product-title"><a href="single-product.html">@product.Name</a></h4>
                            <div class="product-price">
                                @if (product.DiscoutnPrice > 0)
                                {
                                    <span class="price-sale">€@product.DiscoutnPrice</span>
                                    <span class="regular-price">€@product.Price</span>
                                }
                                else
                                {
                                    <span class="price-sale">€@product.Price</span>
                                }
                            </div>
                        </div>
                    </div> <!-- single product -->
                }
            </div>
        }
    </div> <!-- row -->
</div> <!-- product items -->

P129Allup/P129Allup/Views/Shared/_Layout.cshtml
@using P129Allup.Interfaces
@inject ILayoutService layoutService 

@{ 
    List<BasketVM> basketVMs = await layoutService.GetBasket();
    IDictionary<string, string> settings = await layoutService.GetSetting();
}

<!doctype html>
<html class="no-js" lang="en">


<!-- Mirrored from demo.hasthemes.com/allup/allup/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 04 Sep 2020 10:46:32 GMT -->
<head>
    <meta charset="utf-8">

    <!--====== Title ======-->
    <title>Allup - Electronics Responsive eCommerce HTML Template.</title>

    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--====== Favicon Icon ======-->
    <link rel="shortcut icon" href="~/assets/images/favicon.png" type="image/png">


    <!-- CSS
    ============================================ -->
    <!--===== Vendor CSS (Bootstrap & Icon Font) =====-->

    <link rel="stylesheet" href="~/assets/css/plugins/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/css/plugins/ionicons.min.css">
    <link rel="stylesheet" href="~/assets/css/plugins/fontawesome.min.css">

    <!--===== Plugins CSS (All Plugins Files) =====-->

    <link rel="stylesheet" href="~/assets/css/plugins/slick.css">
    <link rel="stylesheet" href="~/assets/css/plugins/animate.css">
    <link rel="stylesheet" href="~/assets/css/plugins/jquery-ui.min.css">
    <link rel="stylesheet" href="~/assets/css/plugins/default.css">

    <!--====== Main Style CSS ======-->
    <link rel="stylesheet" href="~/assets/css/style.css">


    <!--====== Use the minified version files listed below for better performance and remove the files listed above ======-->
    <!-- <link rel="stylesheet" href="~/assets/css/vendor/plugins.min.css">
    <link rel="stylesheet" href="~/assets/css/style.min.css"> -->
    <style>
        @@media only screen and (max-width: 993px) {
            .webelement {
                display: none !important;
            }

            .mobileelement {
                display: block !important;
            }
        }

        @@media only screen and (min-width: 991px) {
            .webelement {
                display: block !important;
            }

            .mobileelement {
                display: none !important;
            }
        }
    </style>

</head>

<body>

    <!--====== PRELOADER PART START ======-->

    <div id="preloader">
        <div class="preloader">
            <span></span>
            <span></span>
        </div>
    </div>

    <!--====== PRELOADER PART ENDS ======-->
    @await Component.InvokeAsync("Header", settings) 

    @RenderBody()

    <!--====== Brand Part Start ======-->

    <div class="brand-area pt-80">
        <div class="container-fluid custom-container">
            <div class="row brand-active">
                <div class="col-lg-2">
                    <div class="single-brand">
                        <a href="#">
                            <img src="~/assets/images/brand/brand-1.jpg" alt="brand">
                        </a>
                    </div> <!-- single brand -->
                </div>
                <div class="col-lg-2">
                    <div class="single-brand">
                        <a href="#">
                            <img src="~/assets/images/brand/brand-2.jpg" alt="brand">
                        </a>
                    </div> <!-- single brand -->
                </div>
                <div class="col-lg-2">
                    <div class="single-brand">
                        <a href="#">
                            <img src="~/assets/images/brand/brand-3.jpg" alt="brand">
                        </a>
                    </div> <!-- single brand -->
                </div>
                <div class="col-lg-2">
                    <div class="single-brand">
                        <a href="#">
                            <img src="~/assets/images/brand/brand-4.jpg" alt="brand">
                        </a>
                    </div> <!-- single brand -->
                </div>
                <div class="col-lg-2">
                    <div class="single-brand">
                        <a href="#">
                            <img src="~/assets/images/brand/brand-5.jpg" alt="brand">
                        </a>
                    </div> <!-- single brand -->
                </div>
                <div class="col-lg-2">
                    <div class="single-brand">
                        <a href="#">
                            <img src="~/assets/images/brand/brand-6.jpg" alt="brand">
                        </a>
                    </div> <!-- single brand -->
                </div>
                <div class="col-lg-2">
                    <div class="single-brand">
                        <a href="#">
                            <img src="~/assets/images/brand/brand-4.jpg" alt="brand">
                        </a>
                    </div> <!-- single brand -->
                </div>
            </div> <!-- row -->
        </div> <!-- container -->
    </div>

    <!--====== Brand Part Ends ======-->
    <!--====== Features Banner Part Start ======-->

    <section class="features-banner-area pt-80 pb-100">
        <div class="container-fluid custom-container">
            <div class="features-banner-wrapper d-flex flex-wrap">
                <div class="single-features-banner d-flex">
                    <div class="banner-icon">
                        <img src="~/assets/images/banner-icon/icon1.png" alt="Icon">
                    </div>
                    <div class="banner-content media-body">
                        <h3 class="banner-title">Free Shipping</h3>
                        <p>Free shipping on all US order</p>
                    </div>
                </div> <!-- single features banner -->
                <div class="single-features-banner d-flex">
                    <div class="banner-icon">
                        <img src="~/assets/images/banner-icon/icon2.png" alt="Icon">
                    </div>
                    <div class="banner-content media-body">
                        <h3 class="banner-title">Support 24/7</h3>
                        <p>Contact us 24 hours a day</p>
                    </div>
                </div> <!-- single features banner -->
                <div class="single-features-banner d-flex">
                    <div class="banner-icon">
                        <img src="~/assets/images/banner-icon/icon3.png" alt="Icon">
                    </div>
                    <div class="banner-content media-body">
                        <h3 class="banner-title">100% Money Back</h3>
                        <p>You have 30 days to Return</p>
                    </div>
                </div> <!-- single features banner -->
                <div class="single-features-banner d-flex">
                    <div class="banner-icon">
                        <img src="~/assets/images/banner-icon/icon4.png" alt="Icon">
                    </div>
                    <div class="banner-content media-body">
                        <h3 class="banner-title">90 Days Return</h3>
                        <p>If goods have problems</p>
                    </div>
                </div> <!-- single features banner -->
                <div class="single-features-banner d-flex">
                    <div class="banner-icon">
                        <img src="~/assets/images/banner-icon/icon5.png" alt="Icon">
                    </div>
                    <div class="banner-content media-body">
                        <h3 class="banner-title">Payment Secure</h3>
                        <p>We ensure secure payment</p>
                    </div>
                </div> <!-- single features banner -->
            </div> <!-- features banner wrapper -->
        </div> <!-- container -->
    </section>

    <!--====== Features Banner Part Ends ======-->
    <!--====== Newsletter Part Start ======-->

    <section class="newsletter-area pt-100 pb-100 bg_cover" style="background-image: url(assets/images/bg-newletter.jpg)">
        <div class="container">
            <div class="row justify-content-end">
                <div class="col-lg-8">
                    <div class="newsletter-content">
                        <h2 class="newsletter-title">Subscribe our newsletter</h2>
                        <p>allup is a powerful eCommerce HTML Template</p>

                        <div class="newsletter-forn">
                            <form action="#">
                                <input type="text" placeholder="Your Email address">
                                <button class="main-btn">Subscribe</button>
                            </form>
                        </div>
                    </div> <!-- newsletter content -->
                </div>
            </div> <!-- row -->
        </div> <!-- container -->
    </section>

    <!--====== Newsletter Part Ends ======-->
    <!--====== Footer Part Start ======-->

    @await Component.InvokeAsync("Footer", settings)

    <!--====== Footer Part Ends ======-->
    <!--====== Quick View Part Start ======-->
    <!-- Modal -->
    <div class="modal fade " id="productQuickModal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                
            </div> <!-- Modal content -->
        </div> <!-- Modal dialog -->
    </div> <!-- Modal -->
    <!--====== Quick View Part Ends ======-->
    <!--====== BACK TOP TOP PART START ======-->

    <a href="#" class="back-to-top"><i class="ion-android-arrow-up"></i></a>

    <!--====== BACK TOP TOP PART ENDS ======-->
    <!--====== Vendors js ======-->
    <script src="~/assets/js/vendor/jquery-1.12.4.min.js"></script>
    <script src="~/assets/js/vendor/modernizr-3.7.1.min.js"></script>

    <!--====== Plugins js ======-->
    <script src="~/assets/js/plugins/popper.min.js"></script>
    <script src="~/assets/js/plugins/bootstrap.min.js"></script>
    <script src="~/assets/js/plugins/slick.min.js"></script>
    <script src="~/assets/js/plugins/jquery.countdown.min.js"></script>
    <script src="~/assets/js/plugins/jquery-ui.min.js"></script>


    <!--====== Use the minified version files listed below for better performance and remove the files listed above ======-->
    <!-- <script src="~/assets/js/plugins.min.js"></script> -->
    <!--====== Main Activation js ======-->
    <script src="~/assets/js/main.js"></script>
    <script src="~/assets/js/custom.js" asp-append-version="true"></script>
    @RenderSection("Script",required:false)

    <script>
        $(document).ready(function () {
            Command: toastr["success"]("Brand Ugurla Yaradildi", "Brand")

            toastr.options = {
                "closeButton": true,
                "debug": false,
                "newestOnTop": false,
                "progressBar": true,
                "positionClass": "toast-top-right",
                "preventDuplicates": false,
                "onclick": null,
                "showDuration": "300",
                "hideDuration": "1000",
                "timeOut": "5000",
                "extendedTimeOut": "1000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut"
            }
        })
    </script>

</body>


<!-- Mirrored from demo.hasthemes.com/allup/allup/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 04 Sep 2020 10:47:16 GMT -->
</html>

P129Allup/P129Allup/Views/Shared/_SearchPartial.cshtml
@model List<Product>

@foreach (Product product in Model)
{
    <li class="list-group-item">
        <img src="assets/images/product/@product.MainImage" style="width:100px" alt="Alternate Text" />
        @product.Name
    </li>
}

P129Allup/P129Allup/Views/Shared/_ValidationPartial.cshtml
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.4/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js"></script>